version: '3'
services:
    kanboard:
        image: kanboard/kanboard:v1.2.26
        volumes:
        - kanboard_data:/var/www/app/data
        - kanboard_plugins:/var/www/app/plugins
        - kanboard_ssl:/etc/nginx/ssl
volumes:
    kanboard_data:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: /mnt/kanboard_data
    kanboard_plugins:
        driver: local
    kanboard_ssl:
        driver: local
