version: '3'
networks:
    default:
        external:
            name: proxy
services:
    kanboard:
        image: kanboard/kanboard:v1.2.26
        volumes:
        - kanboard_data:/var/www/app/data
        - kanboard_plugins:/var/www/app/plugins
        - kanboard_ssl:/etc/nginx/ssl
volumes:
    kanboard_data:
        driver: local
    kanboard_plugins:
        driver: local
    kanboard_ssl:
        driver: local
